### ISSUE TITLE
3.0.1 有好多 warning 提示哇

### ISSUE THREAD

**Issue by kmvan** [seajs/seajs#1518]
```
12:23:41.288 SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function sea.js:335:11
12:23:41.288 SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function sea.js:351:11
12:23:41.288 SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function sea.js:371:11
12:23:41.288 SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function sea.js:400:11
12:23:41.310 ReferenceError: reference to undefined property alias[id] sea.js:160:2
12:23:41.310 ReferenceError: reference to undefined property data.crossorigin sea.js:953:4
12:23:41.672 ReferenceError: reference to undefined property paths[m[1]] sea.js:167:20
```
然后模块们就跑不动了，2.3 反而没事。

**Comment by army8735** [comment]
有demo吗
