### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by nomandia** [seajs/seajs#1602]
可能是个低级问题，但真的是很令人头疼
D:\spm\test>spm install seajs

C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:50
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at co (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:50:14)
    at createPromise (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:30:15)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\bin\spm-install:43:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
我在执行 spm install seajs 时一直报这个错误，不知道怎么回事。我用npm cnpm都试过重新安装 spm，但还是不成，求教@_@

**Comment by nomandia** [comment]
问题解决了，换了新版本的nodejs 便可以。linux下情况相同。
