### ISSUE TITLE
fail to build tensorflow from source 

### ISSUE THREAD

**Issue by Cynthia0629** [seajs/seajs#1720]
Hello,everyone!
    I am new about tensorflow,and I am just trying to build tensorflow from source according to the steps described step by step, but I get the following error, Is there anyone who can help on it? That would be very kind of you! 
   Thank you very much!
 
cynthia@cynthia-pc:~/tensorflow$ ./configure

..........continue........
then the result came with the following......
I guess that maybe something wrong with my bazel ,but I'm new about this,and I'm really no idea how to solve it.

unexpected pipe read status: No such file or directory
Server presumed dead. Now printing '/home/cynthia/.cache/bazel/_bazel_cynthia/581b5660c7c191b39a76e8a607014a30/server/jvm.out':
Java HotSpot(TM) Server VM warning: You have loaded library /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
JNI initialization failed: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch).  Possibly your installation has been corrupted; if this problem persists, try 'rm -fr /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132'.
java.lang.UnsatisfiedLinkError: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
	at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
	at com.google.devtools.build.lib.util.OsUtils.forceJNI(OsUtils.java:55)
	at com.google.devtools.build.lib.util.OsUtils.maybeForceJNI(OsUtils.java:43)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:934)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:838)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:777)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)

**Comment by Cynthia0629** [comment]
Is there anyone who can help?

**Comment by Cynthia0629** [comment]
SOLVED
