### ISSUE TITLE
安装完seajs后，引用模块出现错误！

### ISSUE THREAD

**Issue by oliverliye** [seajs/seajs#511]
你好！
 我用npm install seajs -g 安装seajs模块

安装信息
C:\workspace\fallout\blockcreator>npm install seajs -g
npm http GET https://registry.npmjs.org/seajs
npm http 304 https://registry.npmjs.org/seajs
npm WARN package.json seajs@1.3.0 No README.md file found!
seajs@1.3.0 C:\Documents and Settings\Administrator\Application Data\npm\node_mo
dules\seajs

在代码中require ('seajs')这样引用。出现下面的异常怎么回事，其它的模块这样都没有问题。

module.js:340
    throw err;
          ^
Error: Cannot find module 'seajs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\workspace\fallout\blockcreator\block.js:5:3)
    at Object.<anonymous> (C:\workspace\fallout\blockcreator\block.js:361:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by inJs** [comment]
{ [Error: Cannot find module '/.../node_modules/seajs/dist/require.js'] code: 'MODULE_NOT_FOUND' }

不知啥情况
